import { Inter, Marhey, Tajawal, Jura } from 'next/font/google';
import { notFound } from 'next/navigation';
import { NextIntlClientProvider } from 'next-intl';
import './globals.css';

const jura = Jura({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
});

const tajawal = Tajawal({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
});
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export function generateStaticParams(): { locale: string }[] {
  return [{ locale: 'fr' }, { locale: 'ar' }];
}

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}

export default async function RootLayout({
  children,
  params: { locale },
}: RootLayoutProps) {
  let messages: Record<string, any> | undefined;
  try {
    messages = (await import(`../../messages/${locale}.json`)).default;
  } catch (error) {
    console.log(error);
    // notFound();
  }

  return (
    <html
      dir={locale === 'ar' ? 'rtl' : 'ltr'}
      lang={locale}
      className="bg-white"
    >
      <body className={locale === 'ar' ? tajawal.className : jura.className}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
